In [12]:
import torch
import numpy as np

Check if torch can use the GPU

NOTE: numpy can only handle CPU tensors so trying to do operations with them when using the GPU will result in an error

In [28]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    x = torch.ones(5, device=device)
    
    # Moving the tensor to the device
    y = torch.ones(5)
    y = y.to(device)
    z  = x + y # Done on the GPU
    print(z)
    
    # moving the tensor back to CPU
    z = z.to("cpu")
    z = z.numpy()
    print(z)

In [10]:
x = torch.rand(4,4)

print(x)

y = x.view(-1, 8)
print(y)

tensor([[0.7582, 0.2484, 0.9353, 0.3953],
        [0.4642, 0.2760, 0.6959, 0.7682],
        [0.6857, 0.3719, 0.9029, 0.9402],
        [0.1179, 0.7666, 0.2098, 0.4565]])
tensor([[0.7582, 0.2484, 0.9353, 0.3953, 0.4642, 0.2760, 0.6959, 0.7682],
        [0.6857, 0.3719, 0.9029, 0.9402, 0.1179, 0.7666, 0.2098, 0.4565]])


Converting tensor to numpy array

In [18]:
a = torch.ones(5)
print(a)
b = a.numpy()
print(b)
print(type(b))

# Both point to the same memory location
a.add_(1)
print(a)
print(b)

tensor([1., 1., 1., 1., 1.])
[1. 1. 1. 1. 1.]
<class 'numpy.ndarray'>
tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


Numpy array to tensor

In [23]:
a = np.ones(5)
print(a)
b = torch.from_numpy(a)
print(b)

# Both also point to the same memory location
a += 1
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
